name: Sync with upstream repo

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add upstream remote
      run: |
        git remote add upstream https://codeberg.org/bookstack/api-scripts.git || true

    - name: Fetch upstream changes
      run: |
        git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout main
        git merge upstream/main --no-edit || {
          echo "Merge conflict detected. Creating PR instead."
          exit 1
        }

    - name: Push changes
      run: |
        git push origin main

    - name: Create Pull Request on conflict
      if: failure()
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Sync with upstream repository"
        body: |
          This PR contains changes from the upstream repository at https://codeberg.org/bookstack/api-scripts

          There were merge conflicts that need to be resolved manually.
        branch: sync-upstream
        base: main
